name: Build and Release [Force Rebuild No Deploy] [Manual]

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.actor == 'ayuhito'

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Enable PNPM
        uses: pnpm/action-setup@v2

      - name: Set node version to 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Fetch API # Calls Google Font Metadata to fetch the latest data from Google's Developer API
        run: npx fontsource fetch $GOOGLE_API_KEY
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      - name: Build fonts # Build all updated Google Fonts in repository
        run: npx fontsource build --force

      - name: Generate fontlist
        run: pnpm run fontlist

      - name: Save metadata
        run: pnpm run metadata

      - name: Stage, commit and push files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: "fontsource-bot"
          commit_user_email: "83556432+fontsource-bot@users.noreply.github.com"
          commit_author: "fontsource-bot <83556432+fontsource-bot@users.noreply.github.com>"
          commit_message: "chore(build): update packages [Force] [Manual]"
        continue-on-error: true
