name: Build and Release [Force Rebuild No Deploy] [Manual]

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      # There may be times we exceed runner storage limits
      - name: Free Disk Space
        run: |
          sudo swapoff -a
          sudo rm -rf /swapfile /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h

      - name: Enable PNPM
        uses: pnpm/action-setup@v2

      - name: Set node version to 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Fetch API # Calls Google Font Metadata to fetch the latest data from Google's Developer API
        run: npx fontsource fetch $GOOGLE_API_KEY
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      - name: Build fonts # Build all updated Google Fonts in repository
        run: npx fontsource build --force --ttf

      - name: Generate fontlist
        run: pnpm run fontlist

      - name: Save GFM metadata
        run: pnpm run gfm-metadata

      - name: Save Fontsource metadata
        run: pnpm run metadata

      - name: Stage, commit and push files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: "fontsource-bot"
          commit_user_email: "83556432+fontsource-bot@users.noreply.github.com"
          commit_author: "fontsource-bot <83556432+fontsource-bot@users.noreply.github.com>"
          commit_message: "chore(build): update packages [Manual] [Force] "
        continue-on-error: true
