name: Update Website

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger DB updates
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://beta.fontsource.org/actions/update"
          method: "POST"
          bearerToken: ${{ secrets.WEBSITE_UPDATE_TOKEN }}
          data: '{"fonts": true, "algolia": true, "download": true, "axisRegistry": true, "docs": true}'
          preventFailureOnNoResponse: true
